# zmenu justfile

build:
	zig build

run:
	zig build run

dev:
	printf "alpha\nbeta\ngamma\ndelta\nepsilon\n" | zig build run

test:
	zig build test

clean:
	rm -rf zig-out .zig-cache bin

visual:
	scripts/visual_test.sh
