const search = @import("search.zig");

pub const Color = struct {
    r: f64,
    g: f64,
    b: f64,
    a: f64,
};

pub const Config = struct {
    title: [:0]const u8,
    placeholder: [:0]const u8,
    menu_id: [:0]const u8,
    initial_query: [:0]const u8,
    search: search.Options,
    terminal_mode: bool,
    follow_stdin: bool,
    auto_accept: bool,
    accept_custom_selection: bool,
    window_width: f64,
    window_height: f64,
    max_width: f64,
    max_height: f64,
    field_height: f64,
    padding: f64,
    no_numeric_selection: bool,
    numeric_column_width: f64,
    show_icons: bool,
    icon_column_width: f64,
    show_score: bool,
    score_column_width: f64,
    row_height: f64,
    alternate_rows: bool,
    background_color: ?Color,
    list_background_color: ?Color,
    field_background_color: ?Color,
};

pub fn defaults() Config {
    return .{
        .title = "gmenu",
        .placeholder = "Search",
        .menu_id = "",
        .initial_query = "",
        .search = .{
            .method = .fuzzy,
            .preserve_order = false,
            .limit = 10,
        },
        .terminal_mode = false,
        .follow_stdin = false,
        .auto_accept = false,
        .accept_custom_selection = true,
        .window_width = 600,
        .window_height = 300,
        .max_width = 1920,
        .max_height = 1080,
        .field_height = 24,
        .padding = 8,
        .no_numeric_selection = true,
        .numeric_column_width = 28,
        .show_icons = false,
        .icon_column_width = 48,
        .show_score = false,
        .score_column_width = 60,
        .row_height = 22,
        .alternate_rows = true,
        .background_color = null,
        .list_background_color = null,
        .field_background_color = null,
    };
}
